import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Avatar, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="h-16 flex items-center px-4 border-b">
          <Button asChild variant='ghost' className="font-bold text-xl">
            <Link href='/'>Logo</Link>
          </Button>

          <Button asChild variant='ghost'>
            <Link href='/lp'>service</Link>
          </Button>

          <span className="flex-1"></span>

          <Avatar>
            <AvatarImage src="https://api.dicebear.com/9.x/adventurer/svg?seed=Felix" alt="image"/>
          </Avatar>
        </header>
        <main className="p-4 h-[400px]">{children}</main>
        <footer className="border-t h-16 flex items-center px-4">Footer</footer>
      </body>
    </html>
  );
}
